/**
 * Models Index
 * Exports all models and sets up associations
 */

const { sequelize, testConnection } = require('../config/database');

// Import all models
const Society = require('./Society');
const Block = require('./Block');
const Flat = require('./Flat');
const User = require('./User');
const Role = require('./Role');
const Bill = require('./Bill');
const Payment = require('./Payment');
const Complaint = require('./Complaint');
const Notice = require('./Notice');
const Visitor = require('./Visitor');
const Staff = require('./Staff');
const Amenity = require('./Amenity');
const AmenityBooking = require('./AmenityBooking');
const ChatMessage = require('./ChatMessage');

// Define all associations
const setupAssociations = () => {
  // Society -> Blocks
  Society.hasMany(Block, { foreignKey: 'society_id', as: 'blocks' });
  Block.belongsTo(Society, { foreignKey: 'society_id', as: 'society' });

  // Society -> Flats
  Society.hasMany(Flat, { foreignKey: 'society_id', as: 'flats' });
  Flat.belongsTo(Society, { foreignKey: 'society_id', as: 'society' });

  // Block -> Flats
  Block.hasMany(Flat, { foreignKey: 'block_id', as: 'flats' });
  Flat.belongsTo(Block, { foreignKey: 'block_id', as: 'block' });

  // Society -> Users
  Society.hasMany(User, { foreignKey: 'society_id', as: 'residents' });
  User.belongsTo(Society, { foreignKey: 'society_id', as: 'society' });

  // Flat -> Users
  Flat.hasMany(User, { foreignKey: 'flat_id', as: 'residents' });
  User.belongsTo(Flat, { foreignKey: 'flat_id', as: 'flat' });

  // Role -> Users
  Role.hasMany(User, { foreignKey: 'role_id', as: 'users' });
  User.belongsTo(Role, { foreignKey: 'role_id', as: 'role' });

  // Society -> Roles
  Society.hasMany(Role, { foreignKey: 'society_id', as: 'roles' });
  Role.belongsTo(Society, { foreignKey: 'society_id', as: 'society' });

  // Society -> Bills
  Society.hasMany(Bill, { foreignKey: 'society_id', as: 'bills' });
  Bill.belongsTo(Society, { foreignKey: 'society_id', as: 'society' });

  // Flat -> Bills
  Flat.hasMany(Bill, { foreignKey: 'flat_id', as: 'bills' });
  Bill.belongsTo(Flat, { foreignKey: 'flat_id', as: 'flat' });

  // User (generated by) -> Bills
  User.hasMany(Bill, { foreignKey: 'generated_by', as: 'generatedBills' });
  Bill.belongsTo(User, { foreignKey: 'generated_by', as: 'generator' });

  // Society -> Payments
  Society.hasMany(Payment, { foreignKey: 'society_id', as: 'payments' });
  Payment.belongsTo(Society, { foreignKey: 'society_id', as: 'society' });

  // Flat -> Payments
  Flat.hasMany(Payment, { foreignKey: 'flat_id', as: 'payments' });
  Payment.belongsTo(Flat, { foreignKey: 'flat_id', as: 'flat' });

  // Bill -> Payments
  Bill.hasMany(Payment, { foreignKey: 'bill_id', as: 'payments' });
  Payment.belongsTo(Bill, { foreignKey: 'bill_id', as: 'bill' });

  // User (payer) -> Payments
  User.hasMany(Payment, { foreignKey: 'user_id', as: 'payments' });
  Payment.belongsTo(User, { foreignKey: 'user_id', as: 'payer' });

  // User (created by) -> Payments
  User.hasMany(Payment, { foreignKey: 'created_by', as: 'collectedPayments' });
  Payment.belongsTo(User, { foreignKey: 'created_by', as: 'collector' });

  // Society -> Complaints
  Society.hasMany(Complaint, { foreignKey: 'society_id', as: 'complaints' });
  Complaint.belongsTo(Society, { foreignKey: 'society_id', as: 'society' });

  // Flat -> Complaints
  Flat.hasMany(Complaint, { foreignKey: 'flat_id', as: 'complaints' });
  Complaint.belongsTo(Flat, { foreignKey: 'flat_id', as: 'flat' });

  // User (complainant) -> Complaints
  User.hasMany(Complaint, { foreignKey: 'user_id', as: 'complaints' });
  Complaint.belongsTo(User, { foreignKey: 'user_id', as: 'complainant' });

  // User (assigned to) -> Complaints
  User.hasMany(Complaint, { foreignKey: 'assigned_to', as: 'assignedComplaints' });
  Complaint.belongsTo(User, { foreignKey: 'assigned_to', as: 'assignee' });

  // Society -> Notices
  Society.hasMany(Notice, { foreignKey: 'society_id', as: 'notices' });
  Notice.belongsTo(Society, { foreignKey: 'society_id', as: 'society' });

  // User -> Notices
  User.hasMany(Notice, { foreignKey: 'created_by', as: 'notices' });
  Notice.belongsTo(User, { foreignKey: 'created_by', as: 'author' });

  // Block -> Notices
  Block.hasMany(Notice, { foreignKey: 'target_block_id', as: 'notices' });
  Notice.belongsTo(Block, { foreignKey: 'target_block_id', as: 'targetBlock' });

  // Society -> Visitors
  Society.hasMany(Visitor, { foreignKey: 'society_id', as: 'visitors' });
  Visitor.belongsTo(Society, { foreignKey: 'society_id', as: 'society' });

  // Flat -> Visitors
  Flat.hasMany(Visitor, { foreignKey: 'flat_id', as: 'visitors' });
  Visitor.belongsTo(Flat, { foreignKey: 'flat_id', as: 'flat' });

  // User (entry by) -> Visitors
  User.hasMany(Visitor, { foreignKey: 'entry_by', as: 'visitorEntries' });
  Visitor.belongsTo(User, { foreignKey: 'entry_by', as: 'entryGuard' });

  // User (exit by) -> Visitors
  User.hasMany(Visitor, { foreignKey: 'exit_by', as: 'visitorExits' });
  Visitor.belongsTo(User, { foreignKey: 'exit_by', as: 'exitGuard' });

  // User (approved by) -> Visitors
  User.hasMany(Visitor, { foreignKey: 'approved_by', as: 'approvedVisitors' });
  Visitor.belongsTo(User, { foreignKey: 'approved_by', as: 'approver' });

  // Society -> Staff
  Society.hasMany(Staff, { foreignKey: 'society_id', as: 'staff' });
  Staff.belongsTo(Society, { foreignKey: 'society_id', as: 'society' });

  // User -> Staff
  User.hasOne(Staff, { foreignKey: 'user_id', as: 'staffProfile' });
  Staff.belongsTo(User, { foreignKey: 'user_id', as: 'user' });

  // Society -> Amenities
  Society.hasMany(Amenity, { foreignKey: 'society_id', as: 'amenities' });
  Amenity.belongsTo(Society, { foreignKey: 'society_id', as: 'society' });

  // Society -> AmenityBookings
  Society.hasMany(AmenityBooking, { foreignKey: 'society_id', as: 'amenityBookings' });
  AmenityBooking.belongsTo(Society, { foreignKey: 'society_id', as: 'society' });

  // Amenity -> AmenityBookings
  Amenity.hasMany(AmenityBooking, { foreignKey: 'amenity_id', as: 'bookings' });
  AmenityBooking.belongsTo(Amenity, { foreignKey: 'amenity_id', as: 'amenity' });

  // Flat -> AmenityBookings
  Flat.hasMany(AmenityBooking, { foreignKey: 'flat_id', as: 'amenityBookings' });
  AmenityBooking.belongsTo(Flat, { foreignKey: 'flat_id', as: 'flat' });

  // User -> AmenityBookings
  User.hasMany(AmenityBooking, { foreignKey: 'user_id', as: 'amenityBookings' });
  AmenityBooking.belongsTo(User, { foreignKey: 'user_id', as: 'booker' });

  // User (approved by) -> AmenityBookings
  User.hasMany(AmenityBooking, { foreignKey: 'approved_by', as: 'approvedBookings' });
  AmenityBooking.belongsTo(User, { foreignKey: 'approved_by', as: 'approver' });

  // Payment -> AmenityBooking
  Payment.hasOne(AmenityBooking, { foreignKey: 'payment_id', as: 'booking' });
  AmenityBooking.belongsTo(Payment, { foreignKey: 'payment_id', as: 'payment' });

  // Society -> ChatMessages
  Society.hasMany(ChatMessage, { foreignKey: 'society_id', as: 'chatMessages' });
  ChatMessage.belongsTo(Society, { foreignKey: 'society_id', as: 'society' });

  // User -> ChatMessages
  User.hasMany(ChatMessage, { foreignKey: 'user_id', as: 'chatMessages' });
  ChatMessage.belongsTo(User, { foreignKey: 'user_id', as: 'sender' });

  // Flat -> ChatMessages
  Flat.hasMany(ChatMessage, { foreignKey: 'flat_id', as: 'chatMessages' });
  ChatMessage.belongsTo(Flat, { foreignKey: 'flat_id', as: 'flat' });

  console.log('✅ All model associations set up successfully');
};

// Initialize models with associations
const initializeModels = async () => {
  await testConnection();
  setupAssociations();
  
  // Sync database (create tables)
  if (process.env.NODE_ENV !== 'production') {
    await sequelize.sync({ alter: true });
    console.log('✅ Database synchronized (development mode)');
  }
};

// Export all models and utilities
module.exports = {
  sequelize,
  testConnection,
  initializeModels,
  Society,
  Block,
  Flat,
  User,
  Role,
  Bill,
  Payment,
  Complaint,
  Notice,
  Visitor,
  Staff,
  Amenity,
  AmenityBooking,
  ChatMessage
};
